In [111]:
import pandas as pd
import numpy as np
import mxnet as mx
from sklearn.model_selection import train_test_split

In [120]:
data = pd.read_csv('./data/processed.csv')

In [116]:
data = pd.read_csv('./data/processed.csv')
label = data.readmitted.as_matrix()
data = data.drop(columns=['Unnamed: 0', 'readmitted']).as_matrix()

In [121]:
data

Unnamed: 0  age  time_in_hospital  num_lab_procedures  num_procedures  \
0            4267   55                 8                  77               6   
1            5827   55                 2                  49               1   
2           67608   85                 4                  68               2   
3           17494   85                 3                  46               0   
4            2270   35                 5                  49               0   
5           14180   65                10                  54               2   
6           18234   65                 9                  52               1   
7           15848   45                 2                  50               5   
8           61382   75                14                  21               0   
9            2279   75                12                  47               2   
10           7866   65                 8                  57               6   
11          25911   75                 1                  31               1   
12           1083   65                 2                  15               0   
13           2001   75                 7                  27               3   
14          11049   85                 7                  77               0   
15           2484   65                 4                  47               4   
16          17342   45                 1                  35               5   
17          23541   85                 7                  51               0   
18           4407   65                 4                   2               2   
19           7038   75                 6                  65               2   
20           2005   85                 4                  51               3   
21          10001   35                 1                  58               0   
22          21483   65                 1                  59               0   
23           3294   85                 2                  38               0   
24          22342   55                 2                  64               0   
25          36317   75                 1                  33               2   
26           4333   75                 4                  54               2   
27          18558   75                 2                  39               0   
28          36720   45                 2                  66               0   
29          18390   85                 4                  47               1   
...           ...  ...               ...                 ...             ...   
69620      101755   45                14                  73               6   
69621       99544   75                 2                  38               1   
69622       96047   85                 1                  22               0   
69623       97982   55                 2                  45               2   
69624       96274   65                 2                  61               0   
69625       98897   85                 1                  64               1   
69626       99798   85                 3                  68               1   
69627       99556   15                 2                  44               0   
69628       91913   75                 3                  18               1   
69629       91774   35                 3                  34               1   
69630       93108   85                 2                  37               1   
69631       93052   35                 1                  66               4   
69632       93050   75                 4                  59               1   
69633       96345   65                 4                  19               1   
69634       93742   85                 4                  50               0   
69635       95669   75                 1                  32               0   
69636      100090   45                 6                  69               6   
69637       90717   85                 1                  54               0   
69638  

In [117]:
data

array([[55, 8, 77, ..., 0, 0, 1],
       [55, 2, 49, ..., 1, 1, 0],
       [85, 4, 68, ..., 1, 0, 1],
       ..., 
       [85, 3, 39, ..., 0, 0, 1],
       [45, 14, 69, ..., 0, 0, 1],
       [45, 5, 35, ..., 0, 0, 1]], dtype=object)

In [118]:
train_test_split(data, label, test_size=0.2)

[array([[55, 4, 41, ..., 0, 0, 1],
        [95, 3, 50, ..., 1, 0, 1],
        [85, 12, 15, ..., 1, 0, 1],
        ..., 
        [55, 4, 41, ..., 1, 1, 0],
        [25, 2, 5, ..., 0, 0, 1],
        [55, 4, 51, ..., 0, 0, 1]], dtype=object),
 array([[45, 4, 54, ..., 1, 1, 0],
        [75, 10, 37, ..., 1, 1, 0],
        [85, 4, 45, ..., 1, 1, 0],
        ..., 
        [75, 3, 46, ..., 0, 0, 1],
        [55, 4, 44, ..., 0, 0, 1],
        [75, 6, 30, ..., 1, 0, 1]], dtype=object),
 array([0, 1, 0, ..., 0, 2, 0]),
 array([0, 1, 1, ..., 1, 0, 2])]

In [107]:
label.as_matrix().shape

(69650,)

In [101]:
data.columns

Index(['Unnamed: 0', 'age', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'number_diagnoses',
       'max_glu_serum', 'A1Cresult', 'readmitted', 'number_outpatient_log1p',
       'number_emergency_log1p', 'number_inpatient_log1p',
       'max_glu_serum_is_none', 'A1Cresult_is_none', 'race_?',
       'race_AfricanAmerican', 'race_Asian', 'race_Caucasian', 'race_Hispanic',
       'race_Other', 'gender_Female', 'gender_Male', 'admission_type_id_1',
       'admission_type_id_3', 'admission_type_id_4', 'admission_type_id_5',
       'discharge_disposition_id_1', 'discharge_disposition_id_2',
       'discharge_disposition_id_7', 'discharge_disposition_id_9',
       'discharge_disposition_id_10', 'discharge_disposition_id_18',
       'discharge_disposition_id_22', 'discharge_disposition_id_23',
       'discharge_disposition_id_24', 'discharge_disposition_id_27',
       'discharge_disposi

In [102]:
label = data.readmitted
data = data.drop(['readmitted'], axis=1)

In [103]:
label

0        2
1        0
2        0
3        0
4        0
5        1
6        0
7        1
8        1
9        0
10       0
11       0
12       1
13       1
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       0
        ..
69620    1
69621    0
69622    1
69623    0
69624    0
69625    0
69626    0
69627    0
69628    0
69629    0
69630    0
69631    0
69632    2
69633    0
69634    1
69635    0
69636    0
69637    0
69638    0
69639    1
69640    1
69641    0
69642    0
69643    0
69644    0
69645    0
69646    0
69647    0
69648    1
69649    0
Name: readmitted, Length: 69650, dtype: int64

In [2]:
data = pd.read_csv('./data/data1218.csv')

In [27]:
numpy_matrix = data.as_matrix()

In [28]:
numpy_matrix = numpy_matrix.astype('float32')

In [29]:
np.random.shuffle(numpy_matrix)

In [33]:
numpy_matrix.shape

(99343, 145)

In [70]:
train_data = numpy_matrix[:80000, 1:-1]
train_label = numpy_matrix[:80000, -1].astype('int32')

In [71]:
print(train_data.shape)
print(train_label.shape)

(80000, 143)
(80000,)


In [72]:
test_data = numpy_matrix[80000:, 1:-1]
test_label = numpy_matrix[80000:, -1].astype('int32')

In [73]:
print(test_data.shape)
print(test_label.shape)

(19343, 143)
(19343,)


In [74]:
train_data = mx.nd.array(train_data)
train_label = mx.nd.array(train_label)
test_data = mx.nd.array(test_data)
test_label = mx.nd.array(test_label)

In [75]:
batch_size = 100
ctx = mx.cpu()

In [76]:
train_iter = mx.io.NDArrayIter(data=train_data, label=train_label, batch_size=batch_size, shuffle=True)
test_iter = mx.io.NDArrayIter(data=test_data, label=test_label)

In [77]:
def NaiveNet():
    data = mx.symbol.var(name='data')
    out = mx.symbol.FullyConnected(data=data, num_hidden=512, name='FC1')
    out = mx.symbol.Activation(data=out, act_type='relu')
    out = mx.symbol.FullyConnected(data=out, num_hidden=256, name='FC2')
    out = mx.symbol.Activation(data=out, act_type='relu')
    out = mx.symbol.FullyConnected(data=out, num_hidden=3, name='Out')
    out = mx.symbol.SoftmaxOutput(data=out, name='softmax')
    return out

In [78]:
NNet = NaiveNet()

In [79]:
Model = mx.mod.Module(symbol=NNet, context=ctx)

In [82]:
Model.fit(train_iter, 
          eval_data=test_iter, 
          optimizer='sgd', 
          optimizer_params={'learning_rate':0.1},
          eval_metric='acc',
          batch_end_callback=mx.callback.Speedometer(batch_size, 100),
          num_epoch=10)

/usr/local/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py:502: UserWarning: Parameters already initialized and force_init=False. init_params call ignored.
  allow_missing=allow_missing, force_init=force_init)
